version: '3.8'
services:
  db:
    image: postgres:14.1
    container_name: rest_pg_master
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty78
    ports:
      - '3301:5432'
volumes:
  db:
    driver: local